// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khnonltlzeslfyosvunj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtobm9ubHRsemVzbGZ5b3N2dW5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwMTI3MTgsImV4cCI6MjA4NzU4ODcxOH0.7mIvCiLzOVbSQyzIayyPK1-frm3hXycfcsBPQ02Y4iI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});